login: &login
  username: root

development:
  adapter: mysql
  database: searchgasm_development 
  <<: *login

test:
  adapter: mysql
  database: searchgasm_test
  <<: *login

production:
  adapter: mysql
  database: searchgasm_production
  <<: *login