login: &login
  username: root

development:
  adapter: mysql
  database: searchlogic_development 
  <<: *login

test:
  adapter: mysql
  database: searchlogic_test
  <<: *login

production:
  adapter: mysql
  database: searchlogic_production
  <<: *login